version: "3.8"

networks:
  bbbeasy-network:
    ipam:
      config:
        - subnet: 172.25.0.0/24

services:
  bbbeasy-frontend:
    restart: always
    image: waelsan/bbbeasy-frontend:v1.0.0
    container_name: bbbeasy-frontend
    depends_on:
      - bbbeasy-backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      bbbeasy-network:
        ipv4_address: 172.25.0.20
    volumes:
      - ./docker/logs/nginx:/var/log/nginx:rw
      - ./docker/certbot/www:/var/www/certbot/:ro
      - ./docker/certbot/conf/:/etc/nginx/ssl/:ro
      - ./docker/bbbe-frontend.conf:/etc/nginx/conf.d/bbbe-frontend.conf
  bbbeasy-backend:
    restart: always
    image: waelsan/bbbeasy-backend:v1.0.0
    container_name: bbbeasy-backend
    depends_on:
      - db
      - cache
    networks:
      bbbeasy-network:
        ipv4_address: 172.25.0.21
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./docker/phinx.yml:/var/www/html/bbbeasy-backend/phinx.yml:ro
      - ./docker/www-bbbeasy.conf:/usr/local/etc/php-fpm.d/www-bbbeasy.conf:ro
      - ./docker/default.ini:/var/www/html/bbbeasy-backend/app/config/default.ini:ro
      - ./docker/config-production.ini:/var/www/html/bbbeasy-backend/app/config/config-production.ini:rw
      - ./docker/logs/backend:/var/www/html/bbbeasy-backend/logs/:rw
      - ./docker/logs/nginx:/var/log/nginx:rw
      - ./docker/cache:/var/www/html/bbbeasy-backend/tmp/:rw
  bbbeasy-docs:
    restart: always
    image: waelsan/bbbeasy-docs:v1.0.0
    container_name: bbbeasy-docs
    depends_on:
      - db
      - cache
    networks:
      bbbeasy-network:
        ipv4_address: 172.25.0.22
    volumes:
      - ./docker/logs/nginx:/var/log/nginx:rw
  db:
    restart: always
    image: postgres:15.2-alpine3.17
    container_name: bbbeasy_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bbbeasy
      - POSTGRES_USER=bbbeasy
      - POSTGRES_PASSWORD=bbbeasy
    networks:
      bbbeasy-network:
        ipv4_address: 172.25.0.50
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
  cache:
    restart: always
    image: redis:7.0.9-alpine3.17
    container_name: bbbeasy_cache
    ports:
      - "6379:6379"
    networks:
      bbbeasy-network:
        ipv4_address: 172.25.0.60
  certbot:
    restart: always
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./docker/certbot/www:/var/www/certbot/:rw
      - ./docker/certbot/conf/:/etc/letsencrypt/:rw

