networks:
  bbbeasy-network:
    ipam:
      config:
        - subnet: 172.55.0.0/24

services:
  webserver:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: web
    image: riadvice/bbbeasy-web
    container_name: bbbeasy_nginx
    depends_on:
      - bbbeasy
    ports:
      - "8080:80"
    networks:
      bbbeasy-network:
        ipv4_address: 172.55.0.10
    volumes:
      - ./docker/bbbeasy.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-logs:/var/log/nginx/:rw

  bbbeasy:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: backend
    image: riadvice/bbbeasy
    container_name: bbbeasy_app
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      mail:
        condition: service_started
    environment:
      - APP_ENV=production
    networks:
      bbbeasy-network:
        ipv4_address: 172.55.0.20
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./docker/phinx.yml:/var/www/html/bbbeasy-backend/phinx.yml:ro
      - ./docker/www-bbbeasy.conf:/usr/local/etc/php-fpm.d/www-bbbeasy.conf:ro
      - ./docker/config-production.ini:/var/www/html/bbbeasy-backend/app/config/config-production.ini:ro
      - bbbeasy-logs:/var/www/html/bbbeasy-backend/logs/:rw
      - bbbeasy-cache:/var/www/html/bbbeasy-backend/tmp/:rw
      - bbbeasy-uploads:/var/www/html/bbbeasy-backend/uploads/:rw

  db:
    restart: always
    image: postgres:18-alpine
    container_name: bbbeasy_db
    environment:
      - POSTGRES_DB=bbbeasy
      - POSTGRES_USER=bbbeasy
      - POSTGRES_PASSWORD=bbbeasy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bbbeasy -d bbbeasy"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      bbbeasy-network:
        ipv4_address: 172.55.0.50
    volumes:
      - postgresdata:/var/lib/postgresql

  mail:
    restart: always
    image: axllent/mailpit:latest
    container_name: bbbeasy_mail
    ports:
      - "8025:8025"
    networks:
      bbbeasy-network:
        ipv4_address: 172.55.0.70

  cache:
    restart: always
    image: redis:8-alpine
    container_name: bbbeasy_cache
    networks:
      bbbeasy-network:
        ipv4_address: 172.55.0.60
    volumes:
      - redisdata:/data

volumes:
  bbbeasy-logs:
  bbbeasy-cache:
  bbbeasy-uploads:
  nginx-logs:
  postgresdata:
  redisdata:
