paths:
    migrations: '%%PHINX_CONFIG_DIR%%/db/migrations'
    seeds: '%%PHINX_CONFIG_DIR%%/db/seeds'

environments:
    default_migration_table: phinxlog
    default_database: development
    production:
        adapter: pgsql
        host: bbbeasy_db
        name: bbbeasy
        user: bbbeasy
        pass: W274VlyVDF45EDXzQqsqPnRqDO5iJkrb
        port: 5432
        charset: utf8

    development:
        adapter: pgsql
        host: bbbeasy_db
        name: bbbeasy
        user: bbbeasy
        pass: 'bbbeasy'
        port: 5432
        charset: utf8

    testing:
        adapter: pgsql
        host: bbbeasy_db
        name: bbbeasy_test
        user: bbbeasy_test
        pass: 'bbbeasy_test'
        port: 5432
        charset: utf8

version_order: creation
