upstream bbbeasy_app-upstream
{
    server bbbeasy_app:9000;
}

server
{
    charset utf-8;
    sendfile off;

    listen 80;
    listen [::]:80;

    server_name bbbeasy.test localhost;

    root /var/www/html/bbbeasy-backend/public;
    index index.html;

    access_log /var/log/nginx/bbbeasy-access.log;
    error_log /var/log/nginx/bbbeasy-error.log;

    location /api
    {
        root /var/www/html/bbbeasy-backend/public;
        # Checks whether the requested url exists as a file ($uri) or directory ($uri/) in the root, else redirect to /index.php.
        try_files $uri $uri/ @redirects;
    }

    # Redirect mail bounce and ping
    location ~ ^/mailer-ping/(.*$)
    {
        try_files $uri $uri/ @redirects;
    }

    location @redirects
    {
        rewrite ^ /index.php;
    }

    location ~ \.php$
    {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass bbbeasy_app-upstream;
        fastcgi_index index.php;
        fastcgi_read_timeout 60;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        access_log /var/log/nginx/bbbeasy-backend-access.log;
        error_log /var/log/nginx/bbbeasy-backend-error.log;
    }

    location /docs
    {
        root /var/www/html/bbbeasy-docs;
        index index.html;
        try_files $uri $uri/ /index.html;

        access_log /var/log/nginx/bbbeasy-docs-access.log;
        error_log /var/log/nginx/bbbeasy-docs-error.log;
    }

    location /
    {
        root /var/www/html/bbbeasy-frontend;
        index index.html;
        try_files $uri $uri/ /index.html;

        access_log /var/log/nginx/bbbeasy-frontend-access.log;
        error_log /var/log/nginx/bbbeasy-frontend-error.log;
    }

    # Don't pollute the logs with common requests
    location = /robots.txt
    {
        access_log off; log_not_found off;
    }
    location = /favicon.ico
    {
        access_log off; log_not_found off;
    }

    ##########################
    # Security
    ##########################
    # Hide Nginx version in headers
    server_tokens off;

    # Deny access to dot-files.
    location ~ /\.
    {
        deny all;
        access_log off;
        log_not_found off;
    }

    ##########################
    # Buffers and timeouts
    ##########################
    client_body_buffer_size 10K;
    client_header_buffer_size 1k;
    client_max_body_size 50M;
    large_client_header_buffers 4 512k;

    client_body_timeout 12;
    client_header_timeout 12;
    keepalive_timeout 15;
    send_timeout 10;

    gzip on;
}
