<!-- START FOOTER -->
<div class="footer">

    <table role="presentation" border="0" cellpadding="0" cellspacing="0">
         <tr>

         </tr>
         <tr>
             <td class="content-block powered-by">
                 Sent by   {{@from_name}}.

             </td>
         </tr>
     </table>
</div>
<!-- END FOOTER -->

</div>
</td>
<td>&nbsp;</td>
</tr>
</table>
</body>
</html>