 <include href="mail/common/header.phtml"/>


<span class="preheader">This is preheader text. Some clients will show this text as a preview.</span>
<table border="0" cellpadding="0" cellspacing="0" class="body" role="presentation">
    <tr>
        <td>&nbsp;</td>
        <td class="container">
            <div class="content">

                <!-- START CENTERED WHITE CONTAINER -->
                <table class="main" role="presentation">

                    <!-- START MAIN CONTENT AREA -->
                    <tr>
                        <td class="wrapper">
                            <table border="0" cellpadding="0" cellspacing="0" role="presentation">
                                <tr>
                                    <td>
                                        <p>Hi there,</p>
                                        <p>We've received a request to reset the password for the BBBEasy account
                                            associated with {{ @to }}. No changes have been made to your account
                                            yet.</p>
                                        <p>You can reset your password by clicking the link below: </p>.
                                        <br>

                                        <table border="0" cellpadding="0" cellspacing="0" class="btn btn-primary"
                                               role="presentation">
                                            <tbody>
                                            <tr>
                                                <td align="left">
                                                    <table border="0" cellpadding="0" cellspacing="0"
                                                           role="presentation">
                                                        <tbody>
                                                        <tr>
                                                            <td>
                                                                <a href="http://bbbeasy.test/change-password?token={{ @token }}">Reset
                                                                    your password</a></td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <p style="color: red">NB: this link is valid for 15 minutes it will expires at
                                            {{@expires_at}}.</p>

                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>

                    <!-- END MAIN CONTENT AREA -->
                </table>
                <include href="mail/common/footer.phtml"/>