export const categoriesIcons = {
    'audio': 'AudioOutlined',
    'branding': 'BgColorsOutlined',
    'breakout rooms': 'DeploymentUnitOutlined',
    'general': 'GlobalOutlined',
    'guest policy': 'CoffeeOutlined',
    'language': 'TranslationOutlined',
    'layout': 'LayoutOutlined',
    'learning dashboard': 'FundViewOutlined',
    'lock settings': 'UnlockOutlined',
    'presentation': 'FundOutlined',
    'recording': 'PlayCircleOutlined',
    'screenshare': 'DesktopOutlined',
    'security': 'SafetyOutlined',
    'user experience': 'SmileOutlined',
    'webcams': 'VideoCameraOutlined',
    'whiteboard': 'FundProjectionScreenOutlined',
    'zcaleright': 'ZcaleRight',
};
